server:
  port: 8888
spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3306/springboot
   username: root
   password: 123456
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
#mybatis配置
mybatis:
   typeAliasesPackage: com.xxz.model
   mapper-locations: classpath:mappers/*.xml